export const beansDescriptorContract = {
  address: "0xf519b61DDE4b9855d3764B5A199033dc346C328E",
  abi: [
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: "string", name: "baseURI", type: "string" }],
      name: "BaseURIUpdated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: "bool", name: "enabled", type: "bool" }],
      name: "DataURIToggled",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
        { indexed: true, internalType: "address", name: "newOwner", type: "address" },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      inputs: [
        { internalType: "address", name: "bigHelmetAddress", type: "address" },
        { internalType: "uint8", name: "bigHelmetCount", type: "uint8" },
      ],
      name: "_addBigHelmet",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_color", type: "string" }],
      name: "_addClassOne",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_size", type: "string" }],
      name: "_addClassSize",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_title", type: "string" }],
      name: "_addClassTitle",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_color", type: "string" }],
      name: "_addClassTwo",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_vibe", type: "string" }],
      name: "_addClassVibe",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "gearAddress", type: "address" },
        { internalType: "uint256", name: "gearC", type: "uint256" },
      ],
      name: "_addGear",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "smallHelmetAddress", type: "address" },
        { internalType: "uint8", name: "smallHelmetCount", type: "uint8" },
      ],
      name: "_addSmallHelmet",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "baseBeanAddy",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "baseURI",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "beanSize",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "beanVibeAddy",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "beanVibes",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "bigHelmetCounts",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "bigHelmetLibraries",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          components: [
            { internalType: "uint256", name: "classOne", type: "uint256" },
            { internalType: "uint256", name: "classTwo", type: "uint256" },
            { internalType: "uint256", name: "size", type: "uint256" },
            { internalType: "uint256", name: "helmetLib", type: "uint256" },
            { internalType: "uint256", name: "helmet", type: "uint256" },
            { internalType: "uint256", name: "gearLib", type: "uint256" },
            { internalType: "uint256", name: "gear", type: "uint256" },
            { internalType: "uint256", name: "vibe", type: "uint256" },
          ],
          internalType: "struct IBeansSeeder.Seed",
          name: "seed",
          type: "tuple",
        },
      ],
      name: "buildBeanSvg",
      outputs: [
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "gearLibraryId", type: "uint256" }],
      name: "classGearCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "classGearLibraryCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "sizeCount", type: "uint256" },
        { internalType: "uint256", name: "helmetLibraryId", type: "uint256" },
      ],
      name: "classHelmetCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "sizeType", type: "uint256" }],
      name: "classHelmetLibraryCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "classOne",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "classOneCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "classSizeCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "classTitle",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "classTwo",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "classTwoCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "classVibeCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "tokenId", type: "uint256" },
        {
          components: [
            { internalType: "uint256", name: "classOne", type: "uint256" },
            { internalType: "uint256", name: "classTwo", type: "uint256" },
            { internalType: "uint256", name: "size", type: "uint256" },
            { internalType: "uint256", name: "helmetLib", type: "uint256" },
            { internalType: "uint256", name: "helmet", type: "uint256" },
            { internalType: "uint256", name: "gearLib", type: "uint256" },
            { internalType: "uint256", name: "gear", type: "uint256" },
            { internalType: "uint256", name: "vibe", type: "uint256" },
          ],
          internalType: "struct IBeansSeeder.Seed",
          name: "seed",
          type: "tuple",
        },
      ],
      name: "dataURI",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "gearCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "gearLibraries",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "isDataURIEnabled",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "clsOne", type: "string" },
        { internalType: "string", name: "clsTwo", type: "string" },
        { internalType: "uint256", name: "gearLibraryId", type: "uint256" },
        { internalType: "uint256", name: "itemId", type: "uint256" },
      ],
      name: "pullGearSvg",
      outputs: [
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "clsOne", type: "string" },
        { internalType: "string", name: "clsTwo", type: "string" },
        { internalType: "uint256", name: "sizeId", type: "uint256" },
        { internalType: "uint256", name: "helmetLibraryId", type: "uint256" },
        { internalType: "uint256", name: "itemId", type: "uint256" },
      ],
      name: "pullHelmetSvg",
      outputs: [
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
    {
      inputs: [{ internalType: "address", name: "_basebean", type: "address" }],
      name: "setBaseBean",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_baseURI", type: "string" }],
      name: "setBaseURI",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_beanvibe", type: "address" }],
      name: "setBeanVibe",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "smallHelmetCounts",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "smallHelmetLibraries",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    { inputs: [], name: "toggleDataURIEnabled", outputs: [], stateMutability: "nonpayable", type: "function" },
    {
      inputs: [
        { internalType: "uint256", name: "tokenId", type: "uint256" },
        {
          components: [
            { internalType: "uint256", name: "classOne", type: "uint256" },
            { internalType: "uint256", name: "classTwo", type: "uint256" },
            { internalType: "uint256", name: "size", type: "uint256" },
            { internalType: "uint256", name: "helmetLib", type: "uint256" },
            { internalType: "uint256", name: "helmet", type: "uint256" },
            { internalType: "uint256", name: "gearLib", type: "uint256" },
            { internalType: "uint256", name: "gear", type: "uint256" },
            { internalType: "uint256", name: "vibe", type: "uint256" },
          ],
          internalType: "struct IBeansSeeder.Seed",
          name: "seed",
          type: "tuple",
        },
      ],
      name: "tokenURI",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
} as const;
